#############################################################################################
################################   Analysis of 98 % Simulations     #########################
#############################################################################################

#set working directory
setwd("/Users/ninamasters/measles-spatial-model")
#pull in necessary packages
source("/Users/ninamasters/measles-spatial-model/packages_clustering.R")

sim_98 <- read.csv("/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/98% Vaccination/simulation_summary_data_98.csv")

#change X into time variable
sim_98$time <- as.numeric(substring(sim_98$X, regexpr("time ", sim_98$X) + 5))

# #clear out "two unnamed "X" columns and all "R" columns"X" column
drops <- c("X")
sim_98 <- sim_98[ , !(names(sim_98) %in% drops)]

# # #read in threshold file for key motifs
threshold_motifs_98 <- read.csv("/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/motif_violate_98_threshold.csv")

# # #restrict dataset to only include the motifs that don't violate 1000 people per cell mark
sim_98_threshold <- sim_98[!(sim_98$motif %in% threshold_motifs_98$motif),]

#merge with correct file for summary moran stats
#first - upload the moran key file
moran_list_98<- read.csv("/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Moran Keys/moran_list_motifs_summary_98.csv")
drops <- c("X")
moran_list_98 <- moran_list_98[ , !(names(moran_list_98) %in% drops)]

#now merge 
sim_98_threshold <- merge(sim_98_threshold, moran_list_98, by = "motif")

#now write to file to save with ohter files
write.csv(sim_98_threshold, "/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Full Datasets/simulation_data_98_with_key_threshold_subset.csv")

#############################################################################################
#now we work just with the cleaned, combined file generated by data cleaning/merging R script
sim_98_f <- sim_98_threshold[sim_98_threshold$time == 365,]

write.csv(sim_98_f, "/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Full Datasets/simulation_data_98_with_key_threshold_subset_final_time.csv")

#clear out two unnamed "X" columns and all "R" columns
drops <- c("X", "time")
sim_98_f <- sim_98_f[ , !(names(sim_98_f) %in% drops)]

sim_98_f$CI <- 5120 - sim_98_f$Susceptibles

summary(sim_98_f$CI)

# # #now write this out to a file to use later
#write.csv(sim_95_f, "/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Full Datasets/simulation_data_95_with_key_threshold_subset_final_time.csv")

## now let's plot variance in Moran's I by cum incidence
ggplot(sim_98_f, aes(x = mean_Moran, y = CI)) + geom_point(colour = "blue") + theme_classic() +
  labs(title = "Cumulative Incidence after 1 year across 543 Motifs that do not exceed cell-level population of 1000: Overall Vaccination Coverage at 99%", x = "Variance of Moran's I", y = "Cumulative Incidence", color = "Legend") 

#now we have restricted long-form dataset ot work with.
#first summarize total cases per quadrant of seed case
sim_98_Q1 <- sim_98_f[sim_98_f$run == 1,]
sim_98_Q2 <- sim_98_f[sim_98_f$run == 2,]
sim_98_Q3 <- sim_98_f[sim_98_f$run == 3,]
sim_98_Q4 <- sim_98_f[sim_98_f$run == 4,]
Q1 <- c(1, min(sim_98_Q1$CI), median(sim_98_Q1$CI), mean(sim_98_Q1$CI), max(sim_98_Q1$CI)) 
Q2 <- c(2, min(sim_98_Q2$CI), median(sim_98_Q2$CI), mean(sim_98_Q2$CI), max(sim_98_Q2$CI)) 
Q3 <- c(3, min(sim_98_Q3$CI), median(sim_98_Q3$CI), mean(sim_98_Q3$CI), max(sim_98_Q3$CI)) 
Q4 <- c(4, min(sim_98_Q4$CI), median(sim_98_Q4$CI), mean(sim_98_Q4$CI), max(sim_98_Q4$CI)) 

sum_cases <- as.data.frame(rbind(Q1, Q2, Q3, Q4))
names(sum_cases) <- c("run", "min", "median", "mean", "max")


#now turn level into factor variables
sim_98_f_long$l_1 <- factor(sim_98_f_long$level_1, order = "TRUE", levels = c("0.25", "0.4", "0.58", "0.7", "0.85"))
sim_98_f_long$l_2 <- factor(sim_98_f_long$level_2, order = "TRUE", levels = c("0.25", "0.4", "0.58", "0.7", "0.85"))
sim_98_f_long$l_3 <- factor(sim_98_f_long$level_3, order = "TRUE", levels = c("0.25", "0.4", "0.58", "0.7", "0.85"))
sim_98_f_long$l_4 <- factor(sim_98_f_long$level_4, order = "TRUE", levels = c("0.25", "0.4", "0.58", "0.7", "0.85"))


#four levels
ggplot(sim_98_f, aes(x = factor(level_3), y = CI, fill = factor(level_4))) + geom_boxplot() + theme_dark() + facet_grid(level_2~level_1, labeller = label_both)+
  labs(title = "Fixed Overall Vaccination Coverage at 98: Effect of Clustering on Cumulative Incidence across 543 Motifs that do not violate 1000 individuals per cell", x = "Level 3 Clustering", y = "Cumulative Incidence")  +
  scale_fill_brewer(palette = "Spectral", name="Level 4 Clustering") 

library(ggthemes)

#impact of clustering when level 1 is at 85%
ggplot(sim_98_f[sim_98_f$level_1==0.85,], aes(y = CI, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 98%: Effect of Clustering on Cumulative Incidence across 543 Motifs that do not violate 1000 individuals: Level 1 Clustering = 85%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#impact of clustering when level 1 is at 70%
ggplot(sim_98_f[sim_98_f$level_1==0.70,], aes(y = CI, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 98%: Effect of Clustering on Cumulative Incidence across 543 Motifs that do not violate 1000 individuals: Level 1 Clustering = 70%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#impact of clustering when level 1 is at 58%
ggplot(sim_98_f[sim_98_f$level_1==0.58,], aes(y = CI, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 98%: Effect of Clustering on Cumulative Incidence across 543 Motifs that do not violate 1000 individuals: Level 1 Clustering = 58%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#impact of clustering when level 1 is at 40%
ggplot(sim_98_f[sim_98_f$level_1==0.40,], aes(y = CI, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 98%: Effect of Clustering on Cumulative Incidence across 543 Motifs that do not violate 1000 individuals: Level 1 Clustering = 40%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#impact of clustering when level 1 is at 25%
ggplot(sim_98_f[sim_98_f$level_1==0.25,], aes(y = CI, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 98%: Effect of Clustering on Cumulative Incidence across 543 Motifs that do not violate 1000 individuals: Level 1 Clustering = 25%", x = "Level 2 Clustering", y = "Cumulative Incidence") 


#####################################################################################################
############################# Regression Model Analysis   ###########################################
#####################################################################################################

summary(sim_98_f_long$mean_iso)

#make normalized isolation (iso - min iso)/ (max iso- min iso)
sim_98_f_long$norm_iso <- (sim_98_f_long$mean_iso - 0.0610)/(0.5140-0.0610)

sim_98_f_long$norm_iso_pct <- sim_98_f_long$norm_iso*100


#without moran
lm2 <- lm(CI_val/5120 ~ mean_iso + as.numeric(level_1) + as.numeric(level_2) + as.numeric(level_3)+ as.numeric(level_4), sim_98_f_long)
summary(lm2)

lm_moran <- lm(CI_val/5120 ~ mean_Moran, sim_98_f_long)
summary(lm_moran)

lm3 <- lm(CI_val/5120 ~ norm_iso, sim_98_f_long)
summary(lm3)

l1 <- lm(CI_val/5120 ~ as.numeric(l_1), sim_98_f_long)
summary(l1)

l2 <- lm(CI_val/5120 ~ as.numeric(l_2), sim_98_f_long)
summary(l2)

l3 <- lm(CI_val/5120 ~ as.numeric(l_3), sim_98_f_long)
summary(l3)

l4 <- lm(CI_val/5120 ~ as.numeric(l_4), sim_98_f_long)
summary(l4)

lm_norm <- lm(CI_val/5120 ~ norm_iso + mean_Moran, sim_98_f_long)
summary(lm_norm)

lm4 <- lm(CI_val/5120 ~ mean_Moran + norm_iso + as.numeric(l_1) + as.numeric(l_2) + as.numeric(l_3)+ as.numeric(l_4), sim_98_f_long)
summary(lm4)

################ now again but crude incidence not attack rate

lm <- lm(CI_val ~ mean_Moran, sim_98_f_long)
summary(lm)

lm <- lm(CI_val ~ norm_iso, sim_98_f_long)
summary(lm)

l1 <- lm(CI_val ~ as.numeric(l_1), sim_98_f_long)
summary(l1)

l2 <- lm(CI_val ~ as.numeric(l_2), sim_98_f_long)
summary(l2)

l3 <- lm(CI_val ~ as.numeric(l_3), sim_98_f_long)
summary(l3)

l4 <- lm(CI_val ~ as.numeric(l_4), sim_98_f_long)
summary(l4)

lm4 <- lm(CI_val ~ mean_Moran +norm_iso + as.numeric(l_1) + as.numeric(l_2) + as.numeric(l_3)+ as.numeric(l_4), sim_98_f_long)
summary(lm4)

library(lme4)
library(lmerTest)
# now run linear mixed effects model with random intercepts for motif
lme1 <- lmerTest::lmer(CI_val/5120 ~ norm_iso + as.numeric(level_1) + as.numeric(level_2) + as.numeric(level_3)+ as.numeric(level_4) + (1|motif), data = sim_98_f_long)
summary(lme1)
