#############################################################################################
################################   Analysis of 94 % Simulations     #########################
#############################################################################################
#read in merged, large simulated dataset with 10 different runs of each motif (40 runs per motif, 10 per quadrant) for 94%
# sim_94 <- read.csv("/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Full Datasets/simulation_data_94_combined_with_key.csv")
# 
# #clear out two unnamed "X" columns and all "R" columns
# drops <- c("X", "X.1", "P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9", "P10")
# sim_94 <- sim_94[ , !(names(sim_94) %in% drops)]
# 
# #read in threshold file for key motifs
# threshold_motifs_94 <- read.csv("/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/motif_violate_94_threshold.csv")

# #restrict dataset to only include the motifs that don't violate 1000 people per cell mark
# sim_94_threshold <- sim_94[!(sim_94$motif %in% threshold_motifs_94$motif),]
# 
# #now write this out to a file to use later
# write.csv(sim_94_threshold, "/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Full Datasets/simulation_data_94_with_key_threshold_subset.csv")
# 
# #now we work just with the cleaned, combined file generated by data cleaning/merging R script
# sim_94_f <- sim_94_threshold[sim_94_threshold$time == 365,]
# 
# #now write this out to a file to use later
#write.csv(sim_94_f, "/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Full Datasets/simulation_data_94_with_key_threshold_subset_final_time.csv")

#Just read in final time threshold subset file
sim_94_f <- read.csv("/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Full Datasets/simulation_data_94_with_key_threshold_subset_final_time.csv")
drops <- c("X", "sd_Moran")
sim_94_f <- sim_94_f[ , !(names(sim_94_f) %in% drops)]

#load in isolation index file
iso_94 <- read.csv("/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Isolation Keys/isolation_list_summary_94.csv")
drops <- c("X", "level_1", "level_2", "level_3", "level_4")
iso_94 <- iso_94[ , !(names(iso_94) %in% drops)]

sim_94_f <- merge(sim_94_f, iso_94, by = "motif")

#create new column for cumulative incidence
sim_94_f$CI1 <- 15359- sim_94_f$S1
sim_94_f$CI2 <- 15359 - sim_94_f$S2
sim_94_f$CI3 <- 15359 - sim_94_f$S3
sim_94_f$CI4 <- 15359 - sim_94_f$S4
sim_94_f$CI5 <- 15359 - sim_94_f$S5
sim_94_f$CI6 <- 15359 - sim_94_f$S6
sim_94_f$CI7 <- 15359 - sim_94_f$S7
sim_94_f$CI8 <- 15359 - sim_94_f$S8
sim_94_f$CI9 <- 15359 - sim_94_f$S9
sim_94_f$CI10 <- 15359 - sim_94_f$S10

#how many cases overall?
sum_C1 <- c(1, min(sim_94_f$CI1), median(sim_94_f$CI1), mean(sim_94_f$CI1), max(sim_94_f$CI1)) #C1 cases
sum_C2 <- c(2, min(sim_94_f$CI2), median(sim_94_f$CI2), mean(sim_94_f$CI2), max(sim_94_f$CI2)) #C2 cases
sum_C3 <- c(3, min(sim_94_f$CI3), median(sim_94_f$CI3), mean(sim_94_f$CI3), max(sim_94_f$CI3)) #C2 cases
sum_C4 <- c(4, min(sim_94_f$CI4), median(sim_94_f$CI4), mean(sim_94_f$CI4), max(sim_94_f$CI4)) #C2 cases
sum_C5 <- c(5, min(sim_94_f$CI5), median(sim_94_f$CI5), mean(sim_94_f$CI5), max(sim_94_f$CI5)) #C2 cases
sum_C6 <- c(6, min(sim_94_f$CI6), median(sim_94_f$CI6), mean(sim_94_f$CI6), max(sim_94_f$CI6)) #C2 cases
sum_C7 <- c(7, min(sim_94_f$CI7), median(sim_94_f$CI7), mean(sim_94_f$CI7), max(sim_94_f$CI7)) #C2 cases
sum_C8 <- c(8, min(sim_94_f$CI8), median(sim_94_f$CI8), mean(sim_94_f$CI8), max(sim_94_f$CI8)) #C2 cases
sum_C9 <- c(9, min(sim_94_f$CI9), median(sim_94_f$CI9), mean(sim_94_f$CI9), max(sim_94_f$CI9)) #C2 cases
sum_C10 <- c(10, min(sim_94_f$CI10), median(sim_94_f$CI10), mean(sim_94_f$CI10), max(sim_94_f$CI10)) #C2 cases

sum_cases <- as.data.frame(rbind(sum_C1, sum_C2, sum_C3, sum_C4, sum_C5, sum_C6, sum_C7, sum_C8, sum_C9, sum_C10))
names(sum_cases) <- c("run", "min", "median", "mean", "max")

## now let's plot variance in Moran's I by cum incidence
ggplot(sim_94_f, aes(x = var_Moran, y = CI1)) + geom_point(colour = "blue") + theme_classic() +
  geom_point(aes(x = var_Moran, y = CI2), colour = "red") + 
  geom_point(aes(x = var_Moran, y = CI3), colour = "pink") +
  geom_point(aes(x = var_Moran, y = CI4), colour = "darkred") +
  geom_point(aes(x = var_Moran, y = CI5), colour = "purple") +
  geom_point(aes(x = var_Moran, y = CI6), colour = "green") +
  geom_point(aes(x = var_Moran, y = CI7), colour = "darkgreen") +
  geom_point(aes(x = var_Moran, y = CI8), colour = "violet") +
  geom_point(aes(x = var_Moran, y = CI9), colour = "orange") +
  geom_point(aes(x = var_Moran, y = CI10), colour = "darkblue") +
  labs(title = "Cumulative Incidence after 1 year across 296 Motifs that do not exceed cell-level population of 1000: Overall Vaccination Coverage at 94%", x = "Variance of Moran's I", y = "Cumulative Incidence", color = "Legend") 


## now let's plot Isolation by cum incidence
ggplot(sim_94_f, aes(x = mean_iso, y = CI1)) + geom_point(colour = "blue") + theme_classic() +
  geom_point(aes(x = mean_iso, y = CI2), colour = "red") + 
  geom_point(aes(x = mean_iso, y = CI3), colour = "pink") +
  geom_point(aes(x = mean_iso, y = CI4), colour = "darkred") +
  geom_point(aes(x = mean_iso, y = CI5), colour = "purple") +
  geom_point(aes(x = mean_iso, y = CI6), colour = "green") +
  geom_point(aes(x = mean_iso, y = CI7), colour = "darkgreen") +
  geom_point(aes(x = mean_iso, y = CI8), colour = "violet") +
  geom_point(aes(x = mean_iso, y = CI9), colour = "orange") +
  geom_point(aes(x = mean_iso, y = CI10), colour = "darkblue") +
  labs(title = "Cumulative Incidence after 1 year across 296 Motifs that do not exceed cell-level population of 1000: Overall Vaccination Coverage at 94%", x = "Isolation Index of Starting Motif", y = "Cumulative Incidence", color = "Legend") 

## now let's plot Isolation by cum incidence
ggplot(sim_94_f, aes(x = mean_iso, y = CI1)) + geom_point(colour = "blue") + theme_classic() #+
  geom_point(aes(x = mean_iso, y = CI2), colour = "red") + 
  geom_point(aes(x = mean_iso, y = CI3), colour = "pink") +
  geom_point(aes(x = mean_iso, y = CI4), colour = "darkred") +
  geom_point(aes(x = mean_iso, y = CI5), colour = "purple") +
  geom_point(aes(x = mean_iso, y = CI6), colour = "green") +
  geom_point(aes(x = mean_iso, y = CI7), colour = "darkgreen") +
  geom_point(aes(x = mean_iso, y = CI8), colour = "violet") +
  geom_point(aes(x = mean_iso, y = CI9), colour = "orange") +
  geom_point(aes(x = mean_iso, y = CI10), colour = "darkblue") +
  labs(title = "Cumulative Incidence after 1 year across 296 Motifs that do not exceed cell-level population of 1000: Overall Vaccination Coverage at 94%", x = "Isolation Index of Starting Motif", y = "Cumulative Incidence", color = "Legend") 



## now let's plot Moran's I by cum incidence
ggplot(sim_94_f, aes(x = mean_Moran, y = CI1)) + geom_point(colour = "blue") + theme_classic() +
  geom_point(aes(x = mean_Moran, y = CI2), colour = "red") + 
  geom_point(aes(x = mean_Moran, y = CI3), colour = "pink") +
  geom_point(aes(x = mean_Moran, y = CI4), colour = "darkred") +
  geom_point(aes(x = mean_Moran, y = CI5), colour = "purple") +
  geom_point(aes(x = mean_Moran, y = CI6), colour = "green") +
  geom_point(aes(x = mean_Moran, y = CI7), colour = "darkgreen") +
  geom_point(aes(x = mean_Moran, y = CI8), colour = "violet") +
  geom_point(aes(x = mean_Moran, y = CI9), colour = "orange") +
  geom_point(aes(x = mean_Moran, y = CI10), colour = "darkblue") +
  labs(title = "Cumulative Incidence after 1 year across 296 Motifs that do not exceed cell-level population of 1000: Overall Vaccination Coverage at 94%", x = "Moran's I", y = "Cumulative Incidence", color = "Legend") 

#let's reshape the data so we have all the S, P, CI in long form using reshape2()
library(reshape2)
drops <- c("R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9", "R10","S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10")
sim_94_f<- sim_94_f[ , !(names(sim_94_f) %in% drops)]

#get rid of CI var for Moran S long form
drops <- c("CI1", "CI2", "CI3", "CI4", "CI5", "CI6", "CI7", "CI8", "CI9", "CI10")
sim_94_f_long_Moran_S <- sim_94_f[ , !(names(sim_94_f) %in% drops)]

#get rid of isolation mean and variance for CI long form- will merge after converting
drops <- c("mean_iso", "var_iso", "level_1", "level_2", "level_3", "level_4", "Moran_S_1", "Moran_S_2", "Moran_S_3", "Moran_S_4", "Moran_S_5", "Moran_S_6", "Moran_S_7", "Moran_S_8", "Moran_S_9", "Moran_S_10")
sim_94_f_long_CI <- sim_94_f[ , !(names(sim_94_f) %in% drops)]

sim_94_f_long_Moran_S <- melt(sim_94_f_long_Moran_S, id.vars = c("motif", "run", "mean_iso", "var_iso", "mean_Moran", "var_Moran", "level_1", "level_2", "level_3", "level_4"), variable.name = "Moran_S", value.name = "Moran_S_val")  
sim_94_f_long_CI <- melt(sim_94_f_long_CI, id.vars = c("motif", "run"), variable.name = "CI", value.name = "CI_val")  

#now create new var combo of motif and variable
#first create index of how many runs
sim_94_f_long_Moran_S$sim <- as.numeric(substring(sim_94_f_long_Moran_S$Moran_S, regexpr("Moran_S_", sim_94_f_long_Moran_S$Moran_S) + 8))

#now repeat for the CI case
sim_94_f_long_CI$sim <- as.numeric(substring(sim_94_f_long_CI$CI, regexpr("CI", sim_94_f_long_CI$CI) + 2))


sim_94_f_long_Moran_S$IDmatch <- paste(sim_94_f_long_Moran_S$motif,"-", sim_94_f_long_Moran_S$run, "-", sim_94_f_long_Moran_S$sim)
sim_94_f_long_CI$IDmatch <- paste(sim_94_f_long_CI$motif,"-", sim_94_f_long_CI$run, "-", sim_94_f_long_CI$sim)
drops <- c("motif", "run", "sim")
sim_94_f_long_CI <- sim_94_f_long_CI[ , !(names(sim_94_f_long_CI) %in% drops)]

#now merge the two
sim_94_f_long <- merge(sim_94_f_long_Moran_S, sim_94_f_long_CI, by = "IDmatch")


#calculate number of cases at/above/below outbreak potential

#first create subset-dataset of the number of scenarios in which there was NO outbreak. i.e. cases < 1
num <- unique(sim_94_f_long$motif)
sim_94_no_cases <- sim_94_f_long[sim_94_f_long$CI_val < 1,]
#now how many motifs does this represent
num_no_cases <- unique(sim_94_no_cases$motif)

sim_94_outbreak <- sim_94_f_long[sim_94_f_long$CI_val >5,]
num_outbreak <- unique(sim_94_outbreak$motif)
max(num_outbreak)

#now we have restricted long-form dataset ot work with.
#first summarize total cases per quadrant of seed case
sim_94_Q1 <- sim_94_f_long[sim_94_f_long$run == 1,]
sim_94_Q2 <- sim_94_f_long[sim_94_f_long$run == 2,]
sim_94_Q3 <- sim_94_f_long[sim_94_f_long$run == 3,]
sim_94_Q4 <- sim_94_f_long[sim_94_f_long$run == 4,]
Q1 <- c(1, min(sim_94_Q1$CI_val), median(sim_94_Q1$CI_val), mean(sim_94_Q1$CI_val), max(sim_94_Q1$CI_val)) 
Q2 <- c(2, min(sim_94_Q2$CI_val), median(sim_94_Q2$CI_val), mean(sim_94_Q2$CI_val), max(sim_94_Q2$CI_val)) 
Q3 <- c(3, min(sim_94_Q3$CI_val), median(sim_94_Q3$CI_val), mean(sim_94_Q3$CI_val), max(sim_94_Q3$CI_val)) 
Q4 <- c(4, min(sim_94_Q4$CI_val), median(sim_94_Q4$CI_val), mean(sim_94_Q4$CI_val), max(sim_94_Q4$CI_val)) 

sum_cases <- as.data.frame(rbind(Q1, Q2, Q3, Q4))
names(sum_cases) <- c("run", "min", "median", "mean", "max")

#now turn level into factor variables
sim_94_f_long$l_1 <- factor(sim_94_f_long$level_1, order = "TRUE", levels = c("0.25", "0.4", "0.58", "0.7", "0.85"))
sim_94_f_long$l_2 <- factor(sim_94_f_long$level_2, order = "TRUE", levels = c("0.25", "0.4", "0.58", "0.7", "0.85"))
sim_94_f_long$l_3 <- factor(sim_94_f_long$level_3, order = "TRUE", levels = c("0.25", "0.4", "0.58", "0.7", "0.85"))
sim_94_f_long$l_4 <- factor(sim_94_f_long$level_4, order = "TRUE", levels = c("0.25", "0.4", "0.58", "0.7", "0.85"))


summary(sim_94_f_long$CI_val)
#four levels
ggplot(sim_94_f_long, aes(x = factor(level_3), y = CI_val, fill = factor(level_4))) + geom_boxplot() + theme_dark() + facet_grid(level_2~level_1, labeller = label_both)+
  labs(title = "Fixed Overall Vaccination Coverage at 94%: Effect of Clustering on Cumulative Incidence across 296 Motifs that do not violate 1000 individuals per cell", x = "Level 3 Clustering", y = "Cumulative Incidence")  +
  scale_fill_brewer(palette = "Spectral", name="Level 4 Clustering") 


#four levels
ggplot(sim_94_f_long, aes(x = mean_iso, y = CI_val)) + geom_point() + theme_minimal() + geom_smooth(method="loess", se=TRUE, fullrange=FALSE, level=0.95)
  labs(title = "Fixed Overall Vaccination Coverage at 94%: Effect of Clustering on Cumulative Incidence across 296 Motifs that do not violate 1000 individuals per cell", x = "Mean Isolation Index of Starting Motif", y = "Cumulative Incidence")  

## now let's plot Isolation by cum incidence
ggplot(sim_94_f_long[sim_94_f_long$run==1,], aes(x = mean_iso, y = CI_val)) + geom_point(colour = "blue") + theme_classic() +
  geom_point(aes(x = mean_iso[sim_94_f_long$run==2]+0.001, y = CI_val[sim_94_f_long$run==2]), colour = "green") + 
  geom_point(aes(x = mean_iso[sim_94_f_long$run==3]+0.002, y = CI_val[sim_94_f_long$run==3]), colour = "yellow") +
  geom_point(aes(x = mean_iso[sim_94_f_long$run==4]+0.003, y = CI_val[sim_94_f_long$run==4]), colour = "red") +
labs(title = "Cumulative Incidence after 1 year across 296 Motifs that do not exceed cell-level population of 1000: Overall Vaccination Coverage at 94%", x = "Mean Isolation Index of Starting Motif (shifted by 0.01 for each subsequent run to show differences", y = "Cumulative Incidence", color = "Legend") 

## now let's plot Isolation by cum incidence by run - w loess line
ggplot(sim_94_f_long[sim_94_f_long$run==1,], aes(x = mean_iso, y = CI_val)) + geom_smooth(method = "loess", colour = "blue") + theme_classic() +
  geom_smooth(method = "loess", aes(x = mean_iso[sim_94_f_long$run==2]+0.05, y = CI_val[sim_94_f_long$run==2]), colour = "green") + 
  geom_smooth(method = "loess", aes(x = mean_iso[sim_94_f_long$run==3]+0.09, y = CI_val[sim_94_f_long$run==3]), colour = "yellow") +
  geom_smooth(method = "loess", aes(x = mean_iso[sim_94_f_long$run==4]+0.013, y = CI_val[sim_94_f_long$run==4]), colour = "red") +
  labs(title = "Cumulative Incidence after 1 year across 296 Motifs that do not exceed cell-level population of 1000: Overall Vaccination Coverage at 94%", x = "Mean Isolation Index of Starting Motif (shifted by 0.01 for each subsequent run to show differences", y = "Cumulative Incidence", color = "Legend") 



library(ggthemes)

#impact of clustering when level 1 is at 85%
ggplot(sim_94_f_long[sim_94_f_long$level_1==0.85,], aes(y = CI_val, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 94%: Effect of Clustering on Cumulative Incidence across 296 Motifs that do not violate 1000 individuals: Level 1 Clustering = 85%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#impact of clustering when level 1 is at 70%
ggplot(sim_94_f_long[sim_94_f_long$level_1==0.70,], aes(y = CI_val, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 94%: Effect of Clustering on Cumulative Incidence across 296 Motifs that do not violate 1000 individuals: Level 1 Clustering = 70%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#impact of clustering when level 1 is at 58%
ggplot(sim_94_f_long[sim_94_f_long$level_1==0.58,], aes(y = CI_val, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 94%: Effect of Clustering on Cumulative Incidence across 296 Motifs that do not violate 1000 individuals: Level 1 Clustering = 58%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#impact of clustering when level 1 is at 40%
ggplot(sim_94_f_long[sim_94_f_long$level_1==0.40,], aes(y = CI_val, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 94%: Effect of Clustering on Cumulative Incidence across 296 Motifs that do not violate 1000 individuals: Level 1 Clustering = 40%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#impact of clustering when level 1 is at 25%
ggplot(sim_94_f_long[sim_94_f_long$level_1==0.25,], aes(y = CI_val, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 94%: Effect of Clustering on Cumulative Incidence across 296 Motifs that do not violate 1000 individuals: Level 1 Clustering = 25%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#####################################################################################################
############################# Regression Model Analysis   ###########################################
#####################################################################################################

summary(sim_94_f_long$mean_iso)

#make normalized isolation (iso - min iso)/ (max iso- min iso)
sim_94_f_long$norm_iso <- (sim_94_f_long$mean_iso - 0.0610)/(0.5140-0.0610)

sim_94_f_long$norm_iso_pct <- sim_94_f_long$norm_iso*100


#without moran
lm2 <- lm(CI_val/15359 ~ mean_iso + as.numeric(level_1) + as.numeric(level_2) + as.numeric(level_3)+ as.numeric(level_4), sim_94_f_long)
summary(lm2)

lm_moran <- lm(CI_val/15359 ~ mean_Moran, sim_94_f_long)
summary(lm_moran)

lm3 <- lm(CI_val/15359 ~ norm_iso, sim_94_f_long)
summary(lm3)

l1 <- lm(CI_val/15359 ~ as.numeric(l_1), sim_94_f_long)
summary(l1)

l2 <- lm(CI_val/15359 ~ as.numeric(l_2), sim_94_f_long)
summary(l2)

l3 <- lm(CI_val/15359 ~ as.numeric(l_3), sim_94_f_long)
summary(l3)

l4 <- lm(CI_val/15359 ~ as.numeric(l_4), sim_94_f_long)
summary(l4)

lm_norm <- lm(CI_val/15359 ~ norm_iso + mean_Moran, sim_94_f_long)
summary(lm_norm)

lm4 <- lm(CI_val/15359 ~ mean_Moran + norm_iso + as.numeric(l_1) + as.numeric(l_2) + as.numeric(l_3)+ as.numeric(l_4), sim_94_f_long)
summary(lm4)

################ now again but crude incidence not attack rate

lm <- lm(CI_val ~ mean_Moran, sim_94_f_long)
summary(lm)

lm <- lm(CI_val ~ norm_iso, sim_94_f_long)
summary(lm)

l1 <- lm(CI_val ~ as.numeric(l_1), sim_94_f_long)
summary(l1)

l2 <- lm(CI_val ~ as.numeric(l_2), sim_94_f_long)
summary(l2)

l3 <- lm(CI_val ~ as.numeric(l_3), sim_94_f_long)
summary(l3)

l4 <- lm(CI_val ~ as.numeric(l_4), sim_94_f_long)
summary(l4)

lm4 <- lm(CI_val ~ mean_Moran +norm_iso + as.numeric(l_1) + as.numeric(l_2) + as.numeric(l_3)+ as.numeric(l_4), sim_94_f_long)
summary(lm4)

library(lme4)
library(lmerTest)
# now run linear mixed effects model with random intercepts for motif
lme1 <- lmerTest::lmer(CI_val/15359 ~ norm_iso + as.numeric(level_1) + as.numeric(level_2) + as.numeric(level_3)+ as.numeric(level_4) + (1|motif), data = sim_94_f_long)
summary(lme1)
