#############################################################################################
################################   Analysis of 99 % Simulations     #########################
#############################################################################################

#set working directory
setwd("/Users/ninamasters/measles-spatial-model")
#pull in necessary packages
source("/Users/ninamasters/measles-spatial-model/packages_clustering.R")

# sim_99 <- read.csv("/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Full Datasets/simulation_summary_data_99_combo.csv")
# drops <- c("X.1", "P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9", "P10")
# sim_99 <- sim_99[ , !(names(sim_99) %in% drops)]
# 
# #change X into time variable
# sim_99$time <- as.numeric(substring(sim_99$X, regexpr("time ", sim_99$X) + 5))
# 
# # #clear out X" column
# drops <- c("X")
# sim_99 <- sim_99[ , !(names(sim_99) %in% drops)]
# 
# # # #read in threshold file for key motifs
# threshold_motifs_99 <- c(1,2,6,26,126)
# 
# # # #restrict dataset to only include the motifs that don't violate 1000 people per cell mark
# sim_99_threshold <- sim_99[!(sim_99$motif %in% threshold_motifs_99),]
# 
# #merge with correct file for summary moran stats
# #first - upload the moran key file
# moran_list_99<- read.csv("/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Moran Keys/moran_list_motifs_summary_99.csv")
# drops <- c("X", "sd_Moran")
# moran_list_99 <- moran_list_99[ , !(names(moran_list_99) %in% drops)]
# 
# #now merge 
# sim_99_threshold <- merge(sim_99_threshold, moran_list_99, by = "motif")
# 
# #now write to file to save with other files
# write.csv(sim_99_threshold, "/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Full Datasets/simulation_data_99_with_key_threshold_subset.csv")

#############################################################################################
#now we work just with the cleaned, combined file generated by data cleaning/merging R script

# sim_99_threshold <- read.csv("/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Full Datasets/simulation_data_99_with_key_threshold_subset.csv")
# 
# sim_99_f <- sim_99_threshold[sim_99_threshold$time == 365,]
# 
# drops <- c("X", "time")
# sim_99_f <- sim_99_f[ , !(names(sim_99_f) %in% drops)]

#write out final time file to use for later
#write.csv(sim_99_f, "/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Full Datasets/simulation_data_99_with_key_threshold_subset_final_time.csv")

# NOW START BY LOADING IN THIS FILE
sim_99_f <- read.csv( "/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Full Datasets/simulation_data_99_with_key_threshold_subset_final_time.csv")
drops <- c("X")
sim_99_f <- sim_99_f[ , !(names(sim_99_f) %in% drops)]

#load in isolation index file
iso_99 <- read.csv("/Users/ninamasters/Desktop/Dissertation/Aim 1 - Spatial Model/Simulation Output/Isolation Keys/isolation_list_summary_99.csv")
drops <- c("X", "level_1", "level_2", "level_3", "level_4")
iso_99 <- iso_99[ , !(names(iso_99) %in% drops)]

sim_99_f <- merge(sim_99_f, iso_99, by = "motif")

#clear out two unnamed "X" columns and all "R" columns
drops <- c("X", "time")
sim_99_f <- sim_99_f[ , !(names(sim_99_f) %in% drops)]

sim_99_f$CI1 <- 2560 - sim_99_f$S1
sim_99_f$CI2 <- 2560 - sim_99_f$S2
sim_99_f$CI3 <- 2560 - sim_99_f$S3
sim_99_f$CI4 <- 2560 - sim_99_f$S4
sim_99_f$CI5 <- 2560 - sim_99_f$S5
sim_99_f$CI6 <- 2560 - sim_99_f$S6
sim_99_f$CI7 <- 2560 - sim_99_f$S7
sim_99_f$CI8 <- 2560 - sim_99_f$S8
sim_99_f$CI9 <- 2560 - sim_99_f$S9
sim_99_f$CI10 <- 2560 - sim_99_f$S10


summary(sim_99_f$CI1)

## now let's plot variance in Moran's I by cum incidence
ggplot(sim_99_f, aes(x = mean_Moran, y = CI)) + geom_point(colour = "blue") + theme_classic() +
  labs(title = "Cumulative Incidence after 1 year across 620 Motifs that do not exceed cell-level population of 1000: Overall Vaccination Coverage at 99%", x = "Variance of Moran's I", y = "Cumulative Incidence", color = "Legend") 

#let's reshape the data so we have all the S, P, CI in long form using reshape2()
library(reshape2)
drops <- c("R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9", "R10","S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10")
sim_99_f<- sim_99_f[ , !(names(sim_99_f) %in% drops)]

#get rid of CI var for Moran S long form
drops <- c("CI1", "CI2", "CI3", "CI4", "CI5", "CI6", "CI7", "CI8", "CI9", "CI10")
sim_99_f_long_Moran_S <- sim_99_f[ , !(names(sim_99_f) %in% drops)]

#get rid of isolation mean and variance for CI long form- will merge after converting
drops <- c("mean_iso", "var_iso", "level_1", "level_2", "level_3", "level_4", "Moran_S_1", "Moran_S_2", "Moran_S_3", "Moran_S_4", "Moran_S_5", "Moran_S_6", "Moran_S_7", "Moran_S_8", "Moran_S_9", "Moran_S_10")
sim_99_f_long_CI <- sim_99_f[ , !(names(sim_99_f) %in% drops)]

sim_99_f_long_Moran_S <- melt(sim_99_f_long_Moran_S, id.vars = c("motif", "run", "mean_Moran", "var_Moran", "mean_iso", "var_iso", "level_1", "level_2", "level_3", "level_4"), variable.name = "Moran_S", value.name = "Moran_S_val")  
sim_99_f_long_CI <- melt(sim_99_f_long_CI, id.vars = c("motif", "run"), variable.name = "CI", value.name = "CI_val")  

#now create new var combo of motif and variable
#first create index of how many runs
sim_99_f_long_Moran_S$sim <- as.numeric(substring(sim_99_f_long_Moran_S$Moran_S, regexpr("Moran_S_", sim_99_f_long_Moran_S$Moran_S) + 8))

#now repeat for the CI case
sim_99_f_long_CI$sim <- as.numeric(substring(sim_99_f_long_CI$CI, regexpr("CI", sim_99_f_long_CI$CI) + 2))


sim_99_f_long_Moran_S$IDmatch <- paste(sim_99_f_long_Moran_S$motif,"-", sim_99_f_long_Moran_S$run, "-", sim_99_f_long_Moran_S$sim)
sim_99_f_long_CI$IDmatch <- paste(sim_99_f_long_CI$motif,"-", sim_99_f_long_CI$run, "-", sim_99_f_long_CI$sim)
drops <- c("motif", "run", "sim")
sim_99_f_long_CI <- sim_99_f_long_CI[ , !(names(sim_99_f_long_CI) %in% drops)]

#now merge the two
sim_99_f_long <- merge(sim_99_f_long_Moran_S, sim_99_f_long_CI, by = "IDmatch")

#now we have restricted long-form dataset ot work with.
#first summarize total cases per quadrant of seed case
sim_99_Q1 <- sim_99_f_long[sim_99_f_long$run == 1,]
sim_99_Q2 <- sim_99_f_long[sim_99_f_long$run == 2,]
sim_99_Q3 <- sim_99_f_long[sim_99_f_long$run == 3,]
sim_99_Q4 <- sim_99_f_long[sim_99_f_long$run == 4,]
Q1 <- c(1, min(sim_99_Q1$CI_val), median(sim_99_Q1$CI_val), mean(sim_99_Q1$CI_val), max(sim_99_Q1$CI_val)) 
Q2 <- c(2, min(sim_99_Q2$CI_val), median(sim_99_Q2$CI_val), mean(sim_99_Q2$CI_val), max(sim_99_Q2$CI_val)) 
Q3 <- c(3, min(sim_99_Q3$CI_val), median(sim_99_Q3$CI_val), mean(sim_99_Q3$CI_val), max(sim_99_Q3$CI_val)) 
Q4 <- c(4, min(sim_99_Q4$CI_val), median(sim_99_Q4$CI_val), mean(sim_99_Q4$CI_val), max(sim_99_Q4$CI_val)) 

sum_cases <- as.data.frame(rbind(Q1, Q2, Q3, Q4))
names(sum_cases) <- c("run", "min", "median", "mean", "max")

#four levels
ggplot(sim_99_f_long, aes(x = factor(level_3), y = CI_val, fill = factor(level_4))) + geom_boxplot() + theme_dark() + facet_grid(level_2~level_1, labeller = label_both)+
  labs(title = "Fixed Overall Vaccination Coverage at 99: Effect of Clustering on Cumulative Incidence across 620 Motifs that do not violate 1000 individuals per cell", x = "Level 3 Clustering", y = "Cumulative Incidence")  +
  scale_fill_brewer(palette = "Spectral", name="Level 4 Clustering") 

## now let's plot Isolation by cum incidence
ggplot(sim_99_f_long, aes(x = mean_iso, y = CI_val)) + geom_point(colour = "blue") + theme_classic() + geom_smooth(method = "loess") +
labs(title = "Fixed Overall Vaccination Coverage at 99%: Effect of Clustering on Cumulative Incidence across 620 Motifs that do not violate 1000 individuals: Effect of Isolation", x = "Isolation of Starting Motif", y = "Cumulative Incidence") 

ggplot(sim_99_f_long[sim_99_f_long$run==1,], aes(x = mean_iso, y = CI_val)) + geom_point(colour = "blue") + theme_classic() +
  geom_point(aes(x = mean_iso[sim_99_f_long$run==2]+0.001, y = CI_val[sim_99_f_long$run==2]), colour = "green") + 
  geom_point(aes(x = mean_iso[sim_99_f_long$run==3]+0.002, y = CI_val[sim_99_f_long$run==3]), colour = "yellow") +
  geom_point(aes(x = mean_iso[sim_99_f_long$run==4]+0.003, y = CI_val[sim_99_f_long$run==4]), colour = "red") +
  labs(title = "Cumulative Incidence after 1 year across 620 Motifs that do not exceed cell-level population of 1000: Overall Vaccination Coverage at 99%", x = "Mean Isolation Index of Starting Motif (shifted by 0.01 for each subsequent run to show differences", y = "Cumulative Incidence", color = "Legend") 

ggplot(sim_99_f_long, aes(x= mean_Moran, y= mean_iso)) + geom_point()


#now turn level into factor variables
sim_99_f_long$l_1 <- factor(sim_99_f_long$level_1, order = "TRUE", levels = c("0.25", "0.4", "0.58", "0.7", "0.85"))
sim_99_f_long$l_2 <- factor(sim_99_f_long$level_2, order = "TRUE", levels = c("0.25", "0.4", "0.58", "0.7", "0.85"))
sim_99_f_long$l_3 <- factor(sim_99_f_long$level_3, order = "TRUE", levels = c("0.25", "0.4", "0.58", "0.7", "0.85"))
sim_99_f_long$l_4 <- factor(sim_99_f_long$level_4, order = "TRUE", levels = c("0.25", "0.4", "0.58", "0.7", "0.85"))

library(ggthemes)

#impact of clustering when level 1 is at 85%
ggplot(sim_99_f_long[sim_99_f_long$level_1==0.85,], aes(y = CI_val, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 99%: Effect of Clustering on Cumulative Incidence across 620 Motifs that do not violate 1000 individuals: Level 1 Clustering = 85%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#impact of clustering when level 1 is at 70%
ggplot(sim_99_f_long[sim_99_f_long$level_1==0.70,], aes(y = CI_val, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 99%: Effect of Clustering on Cumulative Incidence across 620 Motifs that do not violate 1000 individuals: Level 1 Clustering = 70%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#impact of clustering when level 1 is at 58%
ggplot(sim_99_f_long[sim_99_f_long$level_1==0.58,], aes(y = CI_val, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 99%: Effect of Clustering on Cumulative Incidence across 620 Motifs that do not violate 1000 individuals: Level 1 Clustering = 58%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#impact of clustering when level 1 is at 40%
ggplot(sim_99_f_long[sim_99_f_long$level_1==0.40,], aes(y = CI_val, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 99%: Effect of Clustering on Cumulative Incidence across 620 Motifs that do not violate 1000 individuals: Level 1 Clustering = 40%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#impact of clustering when level 1 is at 25%
ggplot(sim_99_f_long[sim_99_f_long$level_1==0.25,], aes(y = CI_val, x = factor(level_2), fill = factor(level_4))) + geom_boxplot() + theme_classic() + facet_grid(. ~level_3, labeller = label_both)+
  scale_fill_brewer(palette="Spectral", name = "Level 4 clustering")+
  labs(title = "Fixed Overall Vaccination Coverage at 99%: Effect of Clustering on Cumulative Incidence across 620 Motifs that do not violate 1000 individuals: Level 1 Clustering = 25%", x = "Level 2 Clustering", y = "Cumulative Incidence") 

#####################################################################################################
############################# Regression Model Analysis   ###########################################
#####################################################################################################

summary(sim_99_f_long$mean_iso)

#make normalized isolation (iso - min iso)/ (max iso- min iso)
sim_99_f_long$norm_iso <- (sim_99_f_long$mean_iso - 0.01099)/(0.39759-0.01099)

sim_99_f_long$norm_iso_pct <- sim_99_f_long$norm_iso*100

#with moran
lm1 <- lm(CI_val/(2560) ~ mean_iso + mean_Moran + as.numeric(level_1) + as.numeric(level_2) + as.numeric(level_3)+ as.numeric(level_4), sim_99_f_long)
summary(lm1)

lm1 <- lm(CI_val/(2560) ~ mean_iso + mean_Moran + as.numeric(l_1) + as.numeric(l_2) + as.numeric(l_3)+ as.numeric(l_4), sim_99_f_long)
summary(lm1)

#without moran
lm2 <- lm(CI_val/2560 ~ mean_iso + as.numeric(level_1) + as.numeric(level_2) + as.numeric(level_3)+ as.numeric(level_4), sim_99_f_long)
summary(lm2)

lm_moran <- lm(CI_val/2560 ~ mean_Moran, sim_99_f_long)
summary(lm_moran)

lm3 <- lm(CI_val/2560 ~ norm_iso, sim_99_f_long)
summary(lm3)

l1 <- lm(CI_val/2560 ~ as.numeric(l_1), sim_99_f_long)
summary(l1)

l2 <- lm(CI_val/2560 ~ as.numeric(l_2), sim_99_f_long)
summary(l2)

l3 <- lm(CI_val/2560 ~ as.numeric(l_3), sim_99_f_long)
summary(l3)

l4 <- lm(CI_val/2560 ~ as.numeric(l_4), sim_99_f_long)
summary(l4)

lm_norm <- lm(CI_val/2560 ~ norm_iso + mean_Moran, sim_99_f_long)
summary(lm_norm)

lm4 <- lm(CI_val/2560 ~ norm_iso + mean_Moran + as.numeric(l_1) + as.numeric(l_2) + as.numeric(l_3)+ as.numeric(l_4), sim_99_f_long)
summary(lm4)

################ now again but crude incidence not attack rate

lm <- lm(CI_val ~ mean_Moran, sim_99_f_long)
summary(lm)

lm <- lm(CI_val ~ norm_iso, sim_99_f_long)
summary(lm)

l1 <- lm(CI_val ~ as.numeric(l_1), sim_99_f_long)
summary(l1)

l2 <- lm(CI_val ~ as.numeric(l_2), sim_99_f_long)
summary(l2)

l3 <- lm(CI_val ~ as.numeric(l_3), sim_99_f_long)
summary(l3)

l4 <- lm(CI_val ~ as.numeric(l_4), sim_99_f_long)
summary(l4)

lm4 <- lm(CI_val ~ norm_iso + mean_Moran+ as.numeric(l_1) + as.numeric(l_2) + as.numeric(l_3)+ as.numeric(l_4), sim_99_f_long)
summary(lm4)

library(lme4)
library(lmerTest)
# now run linear mixed effects model with random intercepts for motif
lme1 <- lmerTest::lmer(CI_val/2560 ~ norm_iso + as.numeric(level_1) + as.numeric(level_2) + as.numeric(level_3)+ as.numeric(level_4) + (1|motif), data = sim_99_f_long)
summary(lme1)


